"""empty message

Revision ID: 1e737f3c72a0
Revises: 
Create Date: 2020-05-21 21:39:32.940752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e737f3c72a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.String(length=120), nullable=True),
    sa.Column('query_text', sa.String(length=500), nullable=True),
    sa.Column('query_from', sa.Integer(), nullable=True),
    sa.Column('query_affiliations', sa.String(length=250), nullable=True),
    sa.Column('query_locations', sa.String(length=250), nullable=True),
    sa.Column('user_querying', sa.String(length=250), nullable=True),
    sa.Column('redis_token', sa.String(length=400), nullable=True),
    sa.Column('length_of_results', sa.Integer(), nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('query_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('query_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('query_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('query_affiliations', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('query_locations', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('user_querying', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('redis_token', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('length_of_results', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='result_pkey')
    )
    op.drop_table('results')
    # ### end Alembic commands ###
