"""empty message

Revision ID: 29863bf74267
Revises: 5c6a100be6c0
Create Date: 2020-05-18 18:37:22.585427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29863bf74267'
down_revision = '5c6a100be6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('length_of_results', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'length_of_results')
    # ### end Alembic commands ###
