"""adding query

Revision ID: 3e27a0c34610
Revises: f2d206bc4325
Create Date: 2020-05-17 11:15:32.400592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e27a0c34610'
down_revision = 'f2d206bc4325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.String(length=120), nullable=True),
    sa.Column('query_text', sa.String(length=500), nullable=True),
    sa.Column('query_from', sa.Integer(), nullable=True),
    sa.Column('query_affiliations', sa.String(length=250), nullable=True),
    sa.Column('query_locations', sa.String(length=250), nullable=True),
    sa.Column('user_querying', sa.String(length=250), nullable=True),
    sa.Column('redis_token', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query')
    # ### end Alembic commands ###
