"""empty message

Revision ID: f9cdbaba3834
Revises: 
Create Date: 2020-05-22 11:20:48.653133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9cdbaba3834'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.String(length=120), nullable=True),
    sa.Column('query_text', sa.String(length=500), nullable=True),
    sa.Column('query_from', sa.Integer(), nullable=True),
    sa.Column('query_affiliations', sa.String(length=250), nullable=True),
    sa.Column('query_locations', sa.String(length=250), nullable=True),
    sa.Column('user_querying', sa.String(length=250), nullable=True),
    sa.Column('redis_token', sa.String(length=400), nullable=True),
    sa.Column('length_of_results', sa.Integer(), nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('result')
    # ### end Alembic commands ###
